export { default as AudioPlayer } from '../views/components/audio-player/audio-player'
export { default as ImageZoom } from '../views/components/image-zoom/image-zoom'
export { default as MapGoogle } from '../views/components/map-google/map-google'
export { default as MapMapBox } from '../views/components/map-mapbox/map-mapbox'
export { default as Modal } from '../views/components/modal/modal'
export { default as ShowVideo } from '../views/components/media/show-video'
export { default as VideoBackground } from '../views/components/video-background/video-background'
